// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: 3d_printer

#ifndef UI_SCREEN_1_PRINT_H
#define UI_SCREEN_1_PRINT_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen_1_Print
extern void ui_Screen_1_Print_screen_init(void);
extern void ui_Screen_1_Print_screen_destroy(void);
extern lv_obj_t * ui_Screen_1_Print;
extern lv_obj_t * ui_Background;
extern lv_obj_t * ui_S1_Content_Panel;
extern lv_obj_t * ui_Panel_Buttons_S1;
extern lv_obj_t * ui_BTN_Cancel;
extern lv_obj_t * ui_BTN_Cancel_Top;
extern lv_obj_t * ui_Image_Cancel;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

