// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: 3d_printer

#include "../ui.h"

lv_obj_t * ui_Screen_1_Print = NULL;
lv_obj_t * ui_Background = NULL;
lv_obj_t * ui_S1_Content_Panel = NULL;
lv_obj_t * ui_Panel_Buttons_S1 = NULL;
lv_obj_t * ui_BTN_Cancel = NULL;
lv_obj_t * ui_BTN_Cancel_Top = NULL;
lv_obj_t * ui_Image_Cancel = NULL;
// event funtions

// build funtions

void ui_Screen_1_Print_screen_init(void)
{
    ui_Screen_1_Print = lv_obj_create(NULL);
    lv_obj_set_style_bg_color(ui_Screen_1_Print, lv_color_hex(0x191D26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen_1_Print, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Background = lv_image_create(ui_Screen_1_Print);
    lv_image_set_src(ui_Background, &ui_img_3d_printer_bg_png);
    lv_obj_set_width(ui_Background, 800);
    lv_obj_set_height(ui_Background, 480);
    lv_obj_set_align(ui_Background, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Background, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_image_set_inner_align(ui_Background, LV_IMAGE_ALIGN_TILE);

    ui_S1_Content_Panel = lv_obj_create(ui_Screen_1_Print);
    lv_obj_set_width(ui_S1_Content_Panel, 720);
    lv_obj_set_height(ui_S1_Content_Panel, 430);
    lv_obj_set_align(ui_S1_Content_Panel, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_remove_flag(ui_S1_Content_Panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_S1_Content_Panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_S1_Content_Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_S1_Content_Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_S1_Content_Panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_S1_Content_Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_S1_Content_Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_S1_Content_Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_S1_Content_Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_S1_Content_Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel_Buttons_S1 = lv_obj_create(ui_S1_Content_Panel);
    lv_obj_set_width(ui_Panel_Buttons_S1, 380);
    lv_obj_set_height(ui_Panel_Buttons_S1, 200);
    lv_obj_set_x(ui_Panel_Buttons_S1, -230);
    lv_obj_set_y(ui_Panel_Buttons_S1, -133);
    lv_obj_set_align(ui_Panel_Buttons_S1, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_remove_flag(ui_Panel_Buttons_S1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel_Buttons_S1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel_Buttons_S1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Panel_Buttons_S1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Panel_Buttons_S1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel_Buttons_S1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel_Buttons_S1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel_Buttons_S1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel_Buttons_S1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel_Buttons_S1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BTN_Cancel = lv_image_create(ui_Panel_Buttons_S1);
    lv_image_set_src(ui_BTN_Cancel, &ui_img_btn_print_down_png);
    lv_obj_set_width(ui_BTN_Cancel, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_BTN_Cancel, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_BTN_Cancel, -30);
    lv_obj_set_y(ui_BTN_Cancel, 0);
    lv_obj_set_align(ui_BTN_Cancel, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_BTN_Cancel, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags

    ui_BTN_Cancel_Top = lv_image_create(ui_BTN_Cancel);
    lv_image_set_src(ui_BTN_Cancel_Top, &ui_img_btn_print_top_off_png);
    lv_obj_set_width(ui_BTN_Cancel_Top, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_BTN_Cancel_Top, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_BTN_Cancel_Top, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BTN_Cancel_Top, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_set_style_radius(ui_BTN_Cancel_Top, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_BTN_Cancel_Top, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_BTN_Cancel_Top, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_BTN_Cancel_Top, lv_color_hex(0x00D2FF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_opa(ui_BTN_Cancel_Top, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_width(ui_BTN_Cancel_Top, 9, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_spread(ui_BTN_Cancel_Top, 3, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_offset_x(ui_BTN_Cancel_Top, 0, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_offset_y(ui_BTN_Cancel_Top, 0, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_color(ui_BTN_Cancel_Top, lv_color_hex(0x00D2FF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_opa(ui_BTN_Cancel_Top, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_width(ui_BTN_Cancel_Top, 5, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_spread(ui_BTN_Cancel_Top, 5, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_image_recolor(ui_BTN_Cancel_Top, lv_color_hex(0x67799B), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_image_recolor_opa(ui_BTN_Cancel_Top, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Image_Cancel = lv_image_create(ui_BTN_Cancel_Top);
    lv_image_set_src(ui_Image_Cancel, &ui_img_icn_stop_png);
    lv_obj_set_width(ui_Image_Cancel, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Image_Cancel, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_Image_Cancel, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image_Cancel, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_set_style_image_recolor(ui_Image_Cancel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_image_recolor_opa(ui_Image_Cancel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_Screen_1_Print_screen_destroy(void)
{
    if(ui_Screen_1_Print) lv_obj_del(ui_Screen_1_Print);

    // NULL screen variables
    ui_Screen_1_Print = NULL;
    ui_Background = NULL;
    ui_S1_Content_Panel = NULL;
    ui_Panel_Buttons_S1 = NULL;
    ui_BTN_Cancel = NULL;
    ui_BTN_Cancel_Top = NULL;
    ui_Image_Cancel = NULL;

}
